/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payroll.main;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import payroll.subwins.*;

/**
 *
 * @author ASUS
 */
public class AdminWindow extends javax.swing.JFrame {
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
    Rectangle r = new Rectangle(0,0,d.width,d.height-40);
    
    /**
     * Creates new form AdminWindow
     */
    public AdminWindow() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        table();
        setMaximizedBounds(r);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("lo.png")));
    }
    public AdminWindow(String usr, String frname, String lsname, String di) {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        setMaximizedBounds(r);
        table();
        firstname.setText(frname);
        lastname.setText(lsname);
        level.setText(di);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("lo.png")));
    }
    public void table(){
        try{
            conn = db.db();
            pst = conn.prepareStatement("SELECT * FROM payroll_schema.timemonitor_tbl ORDER BY date_in desc;");
            rs = pst.executeQuery();
            rectable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rectable = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        }
        ;
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        LogOut = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lastname = new javax.swing.JLabel();
        level = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        firstname = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        Maintenance = new javax.swing.JMenu();
        employee = new javax.swing.JMenuItem();
        position = new javax.swing.JMenuItem();
        contribution = new javax.swing.JMenu();
        philhealth = new javax.swing.JMenuItem();
        pagibig = new javax.swing.JMenuItem();
        sss = new javax.swing.JMenuItem();
        tax = new javax.swing.JMenuItem();
        accounts = new javax.swing.JMenuItem();
        timemonitoring = new javax.swing.JMenu();
        dtr = new javax.swing.JMenuItem();
        overtime = new javax.swing.JMenuItem();
        leave = new javax.swing.JMenuItem();
        transaction = new javax.swing.JMenu();
        payroll = new javax.swing.JMenuItem();
        adjusment = new javax.swing.JMenuItem();
        otherdeduction = new javax.swing.JMenuItem();
        month = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        payrollreport = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        philheathreport = new javax.swing.JMenuItem();
        sssreport = new javax.swing.JMenuItem();
        taxreport = new javax.swing.JMenuItem();
        pagibigreport = new javax.swing.JMenuItem();
        dtrreport = new javax.swing.JMenuItem();
        masterlist = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        help = new javax.swing.JMenuItem();
        about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Administrator");
        setUndecorated(true);
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DailyTimeRecord", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jScrollPane1.setAutoscrolls(true);

        rectable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Last Name", "Date In", "Time In", "Date Out", "Time Out", "Status"
            }
        ));
        rectable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        rectable.setShowHorizontalLines(false);
        rectable.setShowVerticalLines(false);
        jScrollPane1.setViewportView(rectable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addContainerGap())
        );

        jCalendar1.setBackground(new java.awt.Color(255, 255, 255));
        jCalendar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Shortcuts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Payroll");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Accounts");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("Employee");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setText("Help");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setText("Master List");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton6.setText("DTR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jCalendar1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(687, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(59, 89, 152));

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));
        jPanel3.setToolTipText("Press to Log out now");
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel3MouseReleased(evt);
            }
        });

        LogOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LogOut.setForeground(new java.awt.Color(255, 255, 255));
        LogOut.setText("Log Out");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogOut)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Logged In as:");

        lastname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lastname.setForeground(new java.awt.Color(255, 255, 255));
        lastname.setText("lname");

        level.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        level.setForeground(new java.awt.Color(255, 255, 255));
        level.setText("division");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("User Level:");

        firstname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        firstname.setForeground(new java.awt.Color(255, 255, 255));
        firstname.setText("fname");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(level)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(firstname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lastname)))
                .addContainerGap(1072, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(firstname)
                            .addComponent(lastname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(level)
                            .addComponent(jLabel9)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jMenuBar2.setBorder(null);

        Maintenance.setText("Maintenance");
        Maintenance.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        employee.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        employee.setText("Employee");
        employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeActionPerformed(evt);
            }
        });
        Maintenance.add(employee);

        position.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        position.setText("Position");
        position.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionActionPerformed(evt);
            }
        });
        Maintenance.add(position);

        contribution.setText("Contribution");

        philhealth.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        philhealth.setText("PhilHealth");
        philhealth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                philhealthActionPerformed(evt);
            }
        });
        contribution.add(philhealth);

        pagibig.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        pagibig.setText("Pag-Ibig");
        pagibig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagibigActionPerformed(evt);
            }
        });
        contribution.add(pagibig);

        sss.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        sss.setText("SSS");
        sss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sssActionPerformed(evt);
            }
        });
        contribution.add(sss);

        tax.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        tax.setText("Tax");
        tax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxActionPerformed(evt);
            }
        });
        contribution.add(tax);

        Maintenance.add(contribution);

        accounts.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        accounts.setText("Accounts");
        accounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountsActionPerformed(evt);
            }
        });
        Maintenance.add(accounts);

        jMenuBar2.add(Maintenance);

        timemonitoring.setText("Time Monitoring");
        timemonitoring.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        dtr.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        dtr.setText("Daily Time Records");
        dtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtrActionPerformed(evt);
            }
        });
        timemonitoring.add(dtr);

        overtime.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        overtime.setText("Over Time");
        overtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overtimeActionPerformed(evt);
            }
        });
        timemonitoring.add(overtime);

        leave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        leave.setText("Leave");
        leave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveActionPerformed(evt);
            }
        });
        timemonitoring.add(leave);

        jMenuBar2.add(timemonitoring);

        transaction.setText("Transaction");
        transaction.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        payroll.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        payroll.setText("Payroll");
        payroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payrollActionPerformed(evt);
            }
        });
        transaction.add(payroll);

        adjusment.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        adjusment.setText("Adjustments");
        adjusment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adjusmentActionPerformed(evt);
            }
        });
        transaction.add(adjusment);

        otherdeduction.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        otherdeduction.setText("Other Deduction");
        otherdeduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherdeductionActionPerformed(evt);
            }
        });
        transaction.add(otherdeduction);

        month.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        month.setText("13th Month");
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });
        transaction.add(month);

        jMenuBar2.add(transaction);

        jMenu1.setText("Reports");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        payrollreport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        payrollreport.setText("Payroll");
        payrollreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payrollreportActionPerformed(evt);
            }
        });
        jMenu1.add(payrollreport);

        jMenu5.setText("Contibution");

        philheathreport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        philheathreport.setText("PhilHealth");
        philheathreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                philheathreportActionPerformed(evt);
            }
        });
        jMenu5.add(philheathreport);

        sssreport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        sssreport.setText("SSS");
        sssreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sssreportActionPerformed(evt);
            }
        });
        jMenu5.add(sssreport);

        taxreport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        taxreport.setText("Tax");
        taxreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxreportActionPerformed(evt);
            }
        });
        jMenu5.add(taxreport);

        pagibigreport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        pagibigreport.setText("Pag-Ibig");
        pagibigreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagibigreportActionPerformed(evt);
            }
        });
        jMenu5.add(pagibigreport);

        jMenu1.add(jMenu5);

        dtrreport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        dtrreport.setText("Daily Time Records");
        dtrreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtrreportActionPerformed(evt);
            }
        });
        jMenu1.add(dtrreport);

        masterlist.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        masterlist.setText("Master List of Employee");
        masterlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterlistActionPerformed(evt);
            }
        });
        jMenu1.add(masterlist);

        jMenuBar2.add(jMenu1);

        jMenu2.setText("Help");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        help.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        help.setText("Help");
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        jMenu2.add(help);

        about.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        about.setText("About ");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        jMenu2.add(about);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeActionPerformed
        // TODO add your handling code here:
        employee mply = new employee(this, true);
        mply.setVisible(true);
    }//GEN-LAST:event_employeeActionPerformed

    private void positionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionActionPerformed
        // TODO add your handling code here:
        position pstn = new position(this, true);
        pstn.setVisible(true);
    }//GEN-LAST:event_positionActionPerformed

    private void philhealthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_philhealthActionPerformed
        // TODO add your handling code here:
        philhealth ph = new philhealth(this,true);
        ph.setVisible(true);
    }//GEN-LAST:event_philhealthActionPerformed

    private void sssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sssActionPerformed
        // TODO add your handling code here:
        sss sss = new sss(this,true);
        sss.setVisible(true);
    }//GEN-LAST:event_sssActionPerformed

    private void taxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxActionPerformed
        // TODO add your handling code here:
        tax tax = new tax(this,true);
        tax.setVisible(true);
    }//GEN-LAST:event_taxActionPerformed

    private void pagibigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagibigActionPerformed
        // TODO add your handling code here:
        pagibig pag = new pagibig(this,true);
        pag.setVisible(true);
    }//GEN-LAST:event_pagibigActionPerformed

    private void accountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountsActionPerformed
        // TODO add your handling code here:
        accounts acc = new accounts(this, true);
        acc.setVisible(true);
    }//GEN-LAST:event_accountsActionPerformed

    private void dtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtrActionPerformed
        // TODO add your handling code here:
        timemonitor tm = new timemonitor(this,true);
        tm.setVisible(true);
    }//GEN-LAST:event_dtrActionPerformed

    private void overtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overtimeActionPerformed
        // TODO add your handling code here:
        overtime ot = new overtime(this,true);
        ot.setVisible(true);
    }//GEN-LAST:event_overtimeActionPerformed

    private void leaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveActionPerformed
        // TODO add your handling code here:
        leave leave = new leave(this,true);
        leave.setVisible(true);
    }//GEN-LAST:event_leaveActionPerformed

    private void payrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payrollActionPerformed
        // TODO add your handling code here:
        payroll pr = new payroll(this,true);
        pr.setVisible(true);
    }//GEN-LAST:event_payrollActionPerformed

    private void adjusmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adjusmentActionPerformed
        // TODO add your handling code here:
        Adjustment adj = new Adjustment(this, true);
        adj.setVisible(true);
    }//GEN-LAST:event_adjusmentActionPerformed

    private void otherdeductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherdeductionActionPerformed
        // TODO add your handling code here:
        otherDeduction od = new otherDeduction(this,true);
        od.setVisible(true);
    }//GEN-LAST:event_otherdeductionActionPerformed

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        // TODO add your handling code here:
        thirteenmonth ttm = new thirteenmonth(this,true);
        ttm.setVisible(true);
    }//GEN-LAST:event_monthActionPerformed

    private void payrollreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payrollreportActionPerformed
        // TODO add your handling code here:
        payrollreport prr = new payrollreport(this,true);
        prr.setVisible(true);
    }//GEN-LAST:event_payrollreportActionPerformed

    private void philheathreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_philheathreportActionPerformed
       // TODO add your handling code here:
       philhealthreport pr = new philhealthreport(this, true);
       pr.setVisible(true);
    }//GEN-LAST:event_philheathreportActionPerformed

    private void sssreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sssreportActionPerformed
        // TODO add your handling code here:
        sssreport pr = new sssreport(this, true);
        pr.setVisible(true);
    }//GEN-LAST:event_sssreportActionPerformed

    private void taxreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxreportActionPerformed
        // TODO add your handling code here:
        taxreport pr = new taxreport(this, true);
        pr.setVisible(true);
    }//GEN-LAST:event_taxreportActionPerformed

    private void pagibigreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagibigreportActionPerformed
        // TODO add your handling code here:
        pagibigreport pr = new pagibigreport(this, true);
       pr.setVisible(true);
    }//GEN-LAST:event_pagibigreportActionPerformed

    private void dtrreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtrreportActionPerformed
        // TODO add your handling code here:
        timemonitorreport tmm = new timemonitorreport(this,true);
        tmm.setVisible(true);
    }//GEN-LAST:event_dtrreportActionPerformed

    private void masterlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterlistActionPerformed
        // TODO add your handling code here:
        mlereport mp = new mlereport(this, true);
        mp.setVisible(true);
    }//GEN-LAST:event_masterlistActionPerformed

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
        jPanel3.setBackground(Color.red);
        LogOut.setForeground(Color.BLACK);
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        // TODO add your handling code here:
        jPanel3.setBackground(new Color(102,153,255));
        LogOut.setForeground(Color.WHITE);
    }//GEN-LAST:event_jPanel3MouseExited

    private void jPanel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseReleased
        // TODO add your handling code here:
        // <editor-fold defaultstate="collapsed" desc="Logged Out Codes Process">
        login login = new login();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        this.dispose();

        Date cd = GregorianCalendar.getInstance().getTime();
        SimpleDateFormat df = new SimpleDateFormat("MM/dd/yyyy");
        String dateString = df.format(cd);

        Date da = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        String timeString = sdf.format(da);

        String ds = dateString;
        String ts = timeString;
        String id = emp.empid;
        String fn = emp.empfn;
        String ln = emp.empln;
        // <editor-fold defaultstate="collapsed" desc="Logged Out Audit">
        try{
            conn = db.db();
            pst = conn.prepareStatement("SELECT * FROM payroll_schema.timemonitor_tbl WHERE id = ? AND date_in = ? AND time_in = ? ;");
            pst.setString(1, id);
            pst.setString(2, time.datein);
            pst.setString(3, time.timein);
            rs = pst.executeQuery();

            while(rs.next()){
                String timein = rs.getString("time_in");
                String datein = rs.getString("date_in");
                
                String hour = timein.substring(0, 2);//first
                String min = timein.substring(3, 5);//first
                
                String hour1 = ts.substring(0, 2);//second
                String min1 = ts.substring(3, 5);//second
                
                Integer hours = Integer.parseInt(hour);//first
                Integer mins = Integer.parseInt(min);//first
                
                Integer hours1 = Integer.parseInt(hour1);//second
                Integer mins1 = Integer.parseInt(min1);//second
                    if(hours == hours1){
                        int timemin = mins1 -mins ;
                        if(timemin < 60){
                            int twh = 1;
                        try{
                            
                            conn = db.db();
                            pst = conn.prepareStatement("update payroll_schema.timemonitor_tbl set date_out = '"+ds+"', time_out='"+ts+"', status = 'Logged Out', twh = "+twh+" where ID = "+id+" AND Status = 'Logged In';");
                            pst.execute();
                            this.dispose();
                        }
                        catch(Exception e){JOptionPane.showMessageDialog(null, e);}
                        try{
                            conn = db.db();
                            pst = conn.prepareStatement("insert into payroll_schema.overtime_tbl values (?,?,?,?,?,?,?,?,?,?);");
                            pst.setString(1, id);
                            pst.setString(2, ln);
                            pst.setString(3, fn);
                            pst.setString(4, String.valueOf(twh));
                            pst.setString(5, "No Validation");
                            pst.setString(6, timein);
                            pst.setString(7, ts);
                            pst.setString(8, datein);
                            pst.setString(9, "Not yet recorded");
                            pst.setString(10, "No Validation");
                            pst.execute();
                        }
                        catch(Exception e){
                            JOptionPane.showMessageDialog(null, e);
                        }
                        }
                        
                    }else if(hours < hours1 && mins1 <= 30){
                        int hou = hours1 - hours;
                        try{
                            System.out.print(min1);
                            conn = db.db();
                            pst = conn.prepareStatement("update payroll_schema.timemonitor_tbl set date_out = '"+ds+"', time_out='"+ts+"', status = 'Logged Out', twh = "+hou+" where ID = "+id+" AND Status = 'Logged In';");
                            pst.execute();
                            this.dispose();
                        }
                        catch(Exception e){JOptionPane.showMessageDialog(null, e);}
                        try{
                            conn = db.db();
                            pst = conn.prepareStatement("insert into payroll_schema.overtime_tbl values (?,?,?,?,?,?,?,?,?,?);");
                            pst.setString(1, id);
                            pst.setString(2, ln);
                            pst.setString(3, fn);
                            pst.setString(4, String.valueOf(hou));
                            pst.setString(5, "No Validation");
                            pst.setString(6, timein);
                            pst.setString(7, ts);
                            pst.setString(8, datein);
                            pst.setString(9, "Not yet recorded");
                            pst.setString(10, "No Validation");
                            pst.execute();
                        }
                        catch(Exception e){
                            JOptionPane.showMessageDialog(null, e);
                        }
                    }else if(hours < hours1 && mins1 > 30){
                            int hou = hours1 - hours + 1;
                        try{
                            System.out.println(hour);
                            System.out.println(hour1);
                            System.out.println(min1);
                            conn = db.db();
                            pst = conn.prepareStatement("update payroll_schema.timemonitor_tbl set date_out = '"+ds+"', time_out='"+ts+"', status = 'Logged Out', twh = "+hou+" where ID = "+id+" AND Status = 'Logged In';");
                            pst.execute();
                            this.dispose();
                        }
                        catch(Exception e){JOptionPane.showMessageDialog(null, e);}
                        try{
                            conn = db.db();
                            pst = conn.prepareStatement("insert into payroll_schema.overtime_tbl values (?,?,?,?,?,?,?,?,?,?);");
                            pst.setString(1, id);
                            pst.setString(2, ln);
                            pst.setString(3, fn);
                            pst.setString(4, String.valueOf(hou));
                            pst.setString(5, "No Validation");
                            pst.setString(6, timein);
                            pst.setString(7, ts);
                            pst.setString(8, datein);
                            pst.setString(9, "Not yet recorded");
                            pst.setString(10, "No Validation");
                            pst.execute();
                        }
                        catch(Exception e){
                            JOptionPane.showMessageDialog(null, e);
                        }
                        
                    }else if(hours1 > 0 && hours1 < hours && mins1 > 30){
                        int twh1 =  ((24 - hours) + hours1)+1;
                        try{
                            
                            conn = db.db();
                            pst = conn.prepareStatement("update payroll_schema.timemonitor_tbl set date_out = '"+ds+"', time_out='"+ts+"', status = 'Logged Out', twh = "+twh1+" where ID = "+id+" AND Status = 'Logged In';");
                            pst.execute();
                            this.dispose();
                        }
                        catch(Exception e){JOptionPane.showMessageDialog(null, e);}
                        try{
                            conn = db.db();
                            pst = conn.prepareStatement("insert into payroll_schema.overtime_tbl values (?,?,?,?,?,?,?,?,?,?);");
                            pst.setString(1, id);
                            pst.setString(2, ln);
                            pst.setString(3, fn);
                            pst.setString(4, String.valueOf(twh1));
                            pst.setString(5, "No Validation");
                            pst.setString(6, timein);
                            pst.setString(7, ts);
                            pst.setString(8, datein);
                            pst.setString(9, "Not yet recorded");
                            pst.setString(10, "No Validation");
                            pst.execute();
                        }
                        catch(Exception e){
                            JOptionPane.showMessageDialog(null, e);
                        }
                    }else if(hours1 > 0 && hours1 < hours && mins1 < 30){
                            int twh1 =  (24 - hours) + hours1;
                        try{
                            conn = db.db();
                            pst = conn.prepareStatement("update payroll_schema.timemonitor_tbl set date_out = '"+ds+"', time_out='"+ts+"', status = 'Logged Out', twh = "+twh1+" where ID = "+id+" AND Status = 'Logged In';");
                            pst.execute();
                            this.dispose();
                        }
                        catch(Exception e){JOptionPane.showMessageDialog(null, e);}
                        try{
                            conn = db.db();
                            pst = conn.prepareStatement("insert into payroll_schema.overtime_tbl values (?,?,?,?,?,?,?,?,?,?);");
                            pst.setString(1, id);
                            pst.setString(2, ln);
                            pst.setString(3, fn);
                            pst.setString(4, String.valueOf(twh1));
                            pst.setString(5, "No Validation");
                            pst.setString(6, timein);
                            pst.setString(7, ts);
                            pst.setString(8, datein);
                            pst.setString(9, "Not yet recorded");
                            pst.setString(10, "No Validation");
                            pst.execute();
                        }
                        catch(Exception e){
                            JOptionPane.showMessageDialog(null, e);
                        }
                    }
            }
        }
        catch(Exception e){JOptionPane.showMessageDialog(null, e);}

        // </editor-fold>
        //</editor-fold>
    }//GEN-LAST:event_jPanel3MouseReleased

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        // TODO add your handling code here:
        Help hlp = new Help(this,true);
        hlp.setVisible(true);
    }//GEN-LAST:event_helpActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // TODO add your handling code here:
        About about = new About(this,true);
        about.setVisible(true);
    }//GEN-LAST:event_aboutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        payroll pr = new payroll(this,true);
        pr.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        timemonitor tm = new timemonitor(this,true);
        tm.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        accounts acc = new accounts(this, true);
        acc.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         mlereport mp = new mlereport(this, true);
        mp.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        employee mply = new employee(this, true);
        mply.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Help hlp = new Help(this,true);
        hlp.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogOut;
    private javax.swing.JMenu Maintenance;
    private javax.swing.JMenuItem about;
    private javax.swing.JMenuItem accounts;
    private javax.swing.JMenuItem adjusment;
    private javax.swing.JMenu contribution;
    private javax.swing.JMenuItem dtr;
    private javax.swing.JMenuItem dtrreport;
    private javax.swing.JMenuItem employee;
    private javax.swing.JLabel firstname;
    private javax.swing.JMenuItem help;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastname;
    private javax.swing.JMenuItem leave;
    private javax.swing.JLabel level;
    private javax.swing.JMenuItem masterlist;
    private javax.swing.JMenuItem month;
    private javax.swing.JMenuItem otherdeduction;
    private javax.swing.JMenuItem overtime;
    private javax.swing.JMenuItem pagibig;
    private javax.swing.JMenuItem pagibigreport;
    private javax.swing.JMenuItem payroll;
    private javax.swing.JMenuItem payrollreport;
    private javax.swing.JMenuItem philhealth;
    private javax.swing.JMenuItem philheathreport;
    private javax.swing.JMenuItem position;
    private javax.swing.JTable rectable;
    private javax.swing.JMenuItem sss;
    private javax.swing.JMenuItem sssreport;
    private javax.swing.JMenuItem tax;
    private javax.swing.JMenuItem taxreport;
    private javax.swing.JMenu timemonitoring;
    private javax.swing.JMenu transaction;
    // End of variables declaration//GEN-END:variables

}