/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payroll.main;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import payroll.subwins.*;
import payroll.basecodes.*;
import interfaces.*;

/**
 *
 * @author ASUS
 */
public class AdminWindow extends javax.swing.JFrame implements IRetrieveDetails {
    
    ResultSet result;
    DataType[] values;
    
    Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
    Rectangle rectangle = new Rectangle(0,0,dimension.width,dimension.height-40);
    
    /**
     * Creates new form AdminWindow
     */
    public AdminWindow()
    {
        SetupWindow();
    }
    
    public AdminWindow(String id, String full_name) {
        SetupWindow();
        FullNameText.setText(full_name);
    }
    
    @Override
    public void RetrieveDetails(){
        String query = "SELECT * FROM "+Database.logTable+";";
        result = Database.SendQuery(query);
        rectable.setModel(DbUtils.resultSetToTableModel(result));
    }
    
    private void SetupWindow()
    {
        initComponents();
        setLocationRelativeTo(null);
//        setExtendedState(MAXIMIZED_BOTH);
        RetrieveDetails();
//        setMaximizedBounds(rectangle);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("lo.png")));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rectable = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        }
        ;
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        BottomPanel = new javax.swing.JPanel();
        LogOutBtnBg = new javax.swing.JPanel();
        LogOutText = new javax.swing.JLabel();
        LoggedAsDesc = new javax.swing.JLabel();
        FullNameText = new javax.swing.JLabel();
        UserLevelDescText = new javax.swing.JLabel();
        UserLevelText = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        Maintenance = new javax.swing.JMenu();
        employee = new javax.swing.JMenuItem();
        position = new javax.swing.JMenuItem();
        contribution = new javax.swing.JMenu();
        philhealth = new javax.swing.JMenuItem();
        pagibig = new javax.swing.JMenuItem();
        sss = new javax.swing.JMenuItem();
        tax = new javax.swing.JMenuItem();
        accounts = new javax.swing.JMenuItem();
        timemonitoring = new javax.swing.JMenu();
        dtr = new javax.swing.JMenuItem();
        overtime = new javax.swing.JMenuItem();
        leave = new javax.swing.JMenuItem();
        transaction = new javax.swing.JMenu();
        payroll = new javax.swing.JMenuItem();
        adjusment = new javax.swing.JMenuItem();
        otherdeduction = new javax.swing.JMenuItem();
        month = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        payrollreport = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        philheathreport = new javax.swing.JMenuItem();
        sssreport = new javax.swing.JMenuItem();
        taxreport = new javax.swing.JMenuItem();
        pagibigreport = new javax.swing.JMenuItem();
        dtrreport = new javax.swing.JMenuItem();
        masterlist = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        help = new javax.swing.JMenuItem();
        about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Administrator");
        setUndecorated(true);
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DailyTimeRecord", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jScrollPane1.setAutoscrolls(true);

        rectable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Last Name", "Date In", "Time In", "Date Out", "Time Out", "Status"
            }
        ));
        rectable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(rectable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addContainerGap())
        );

        jCalendar1.setBackground(new java.awt.Color(255, 255, 255));
        jCalendar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Shortcuts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Payroll");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Accounts");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("Employee");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setText("Help");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setText("Master List");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton6.setText("DTR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jCalendar1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(2, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(2, Short.MAX_VALUE))
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        BottomPanel.setBackground(new java.awt.Color(59, 89, 152));

        LogOutBtnBg.setBackground(new java.awt.Color(102, 153, 255));
        LogOutBtnBg.setToolTipText("Press to Log out now");
        LogOutBtnBg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogOutBtnBgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogOutBtnBgMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LogOutBtnBgMouseReleased(evt);
            }
        });

        LogOutText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LogOutText.setForeground(new java.awt.Color(255, 255, 255));
        LogOutText.setText("Log Out");

        javax.swing.GroupLayout LogOutBtnBgLayout = new javax.swing.GroupLayout(LogOutBtnBg);
        LogOutBtnBg.setLayout(LogOutBtnBgLayout);
        LogOutBtnBgLayout.setHorizontalGroup(
            LogOutBtnBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogOutBtnBgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogOutText)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        LogOutBtnBgLayout.setVerticalGroup(
            LogOutBtnBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogOutBtnBgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogOutText, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        LoggedAsDesc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LoggedAsDesc.setForeground(new java.awt.Color(255, 255, 255));
        LoggedAsDesc.setText("Logged In as:");

        FullNameText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        FullNameText.setForeground(new java.awt.Color(255, 255, 255));
        FullNameText.setText("fname");

        UserLevelDescText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        UserLevelDescText.setForeground(new java.awt.Color(255, 255, 255));
        UserLevelDescText.setText("Access Level:");

        UserLevelText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        UserLevelText.setForeground(new java.awt.Color(255, 255, 255));
        UserLevelText.setText("division");

        javax.swing.GroupLayout BottomPanelLayout = new javax.swing.GroupLayout(BottomPanel);
        BottomPanel.setLayout(BottomPanelLayout);
        BottomPanelLayout.setHorizontalGroup(
            BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogOutBtnBg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LoggedAsDesc)
                    .addComponent(UserLevelDescText))
                .addGap(18, 18, 18)
                .addGroup(BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FullNameText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UserLevelText, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE))
                .addContainerGap())
        );
        BottomPanelLayout.setVerticalGroup(
            BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BottomPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LoggedAsDesc)
                            .addComponent(FullNameText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UserLevelText)
                            .addComponent(UserLevelDescText)))
                    .addComponent(LogOutBtnBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(BottomPanel, java.awt.BorderLayout.PAGE_END);

        jMenuBar2.setBorder(null);

        Maintenance.setText("Maintenance");
        Maintenance.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        employee.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        employee.setText("Employee");
        employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeActionPerformed(evt);
            }
        });
        Maintenance.add(employee);

        position.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        position.setText("Position");
        position.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionActionPerformed(evt);
            }
        });
        Maintenance.add(position);

        contribution.setText("Contribution");

        philhealth.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        philhealth.setText("PhilHealth");
        philhealth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                philhealthActionPerformed(evt);
            }
        });
        contribution.add(philhealth);

        pagibig.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        pagibig.setText("Pag-Ibig");
        pagibig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagibigActionPerformed(evt);
            }
        });
        contribution.add(pagibig);

        sss.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        sss.setText("SSS");
        sss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sssActionPerformed(evt);
            }
        });
        contribution.add(sss);

        tax.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        tax.setText("Tax");
        tax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxActionPerformed(evt);
            }
        });
        contribution.add(tax);

        Maintenance.add(contribution);

        accounts.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        accounts.setText("Accounts");
        accounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountsActionPerformed(evt);
            }
        });
        Maintenance.add(accounts);

        jMenuBar2.add(Maintenance);

        timemonitoring.setText("Time Monitoring");
        timemonitoring.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        dtr.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        dtr.setText("Daily Time Records");
        dtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtrActionPerformed(evt);
            }
        });
        timemonitoring.add(dtr);

        overtime.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        overtime.setText("Over Time");
        overtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overtimeActionPerformed(evt);
            }
        });
        timemonitoring.add(overtime);

        leave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        leave.setText("Leave");
        leave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveActionPerformed(evt);
            }
        });
        timemonitoring.add(leave);

        jMenuBar2.add(timemonitoring);

        transaction.setText("Transaction");
        transaction.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        payroll.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        payroll.setText("Payroll");
        payroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payrollActionPerformed(evt);
            }
        });
        transaction.add(payroll);

        adjusment.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        adjusment.setText("Adjustments");
        adjusment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adjusmentActionPerformed(evt);
            }
        });
        transaction.add(adjusment);

        otherdeduction.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        otherdeduction.setText("Other Deduction");
        otherdeduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherdeductionActionPerformed(evt);
            }
        });
        transaction.add(otherdeduction);

        month.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        month.setText("13th Month");
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });
        transaction.add(month);

        jMenuBar2.add(transaction);

        jMenu1.setText("Reports");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        payrollreport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        payrollreport.setText("Payroll");
        payrollreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payrollreportActionPerformed(evt);
            }
        });
        jMenu1.add(payrollreport);

        jMenu5.setText("Contibution");

        philheathreport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        philheathreport.setText("PhilHealth");
        philheathreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                philheathreportActionPerformed(evt);
            }
        });
        jMenu5.add(philheathreport);

        sssreport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        sssreport.setText("SSS");
        sssreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sssreportActionPerformed(evt);
            }
        });
        jMenu5.add(sssreport);

        taxreport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        taxreport.setText("Tax");
        taxreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxreportActionPerformed(evt);
            }
        });
        jMenu5.add(taxreport);

        pagibigreport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        pagibigreport.setText("Pag-Ibig");
        pagibigreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagibigreportActionPerformed(evt);
            }
        });
        jMenu5.add(pagibigreport);

        jMenu1.add(jMenu5);

        dtrreport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        dtrreport.setText("Daily Time Records");
        dtrreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtrreportActionPerformed(evt);
            }
        });
        jMenu1.add(dtrreport);

        masterlist.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        masterlist.setText("Master List of Employee");
        masterlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterlistActionPerformed(evt);
            }
        });
        jMenu1.add(masterlist);

        jMenuBar2.add(jMenu1);

        jMenu2.setText("Help");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        help.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        help.setText("Help");
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        jMenu2.add(help);

        about.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        about.setText("About ");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        jMenu2.add(about);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeActionPerformed
        // TODO add your handling code here:
        AppWindow.ShowPanel(new employee(this, true));
    }//GEN-LAST:event_employeeActionPerformed

    private void positionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionActionPerformed
        // TODO add your handling code here:
        AppWindow.ShowPanel(new position(this, true));
    }//GEN-LAST:event_positionActionPerformed

    private void philhealthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_philhealthActionPerformed
        // TODO add your handling code here:
        AppWindow.ShowPanel(new philhealth(this, true));
    }//GEN-LAST:event_philhealthActionPerformed

    private void sssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sssActionPerformed
        // TODO add your handling code here:
        AppWindow.ShowPanel(new sss(this, true));
    }//GEN-LAST:event_sssActionPerformed

    private void taxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxActionPerformed
        // TODO add your handling code here:
        AppWindow.ShowPanel(new tax(this, true));
    }//GEN-LAST:event_taxActionPerformed

    private void pagibigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagibigActionPerformed
        // TODO add your handling code here:
        AppWindow.ShowPanel(new pagibig(this, true));
    }//GEN-LAST:event_pagibigActionPerformed

    private void accountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountsActionPerformed
        // TODO add your handling code here:
        AppWindow.ShowPanel(new accounts(this, true));
    }//GEN-LAST:event_accountsActionPerformed

    private void dtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtrActionPerformed
        // TODO add your handling code here:
        AppWindow.ShowPanel(new timemonitor(this, true));
    }//GEN-LAST:event_dtrActionPerformed

    private void overtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overtimeActionPerformed
        // TODO add your handling code here:
        AppWindow.ShowPanel(new overtime(this, true));
    }//GEN-LAST:event_overtimeActionPerformed

    private void leaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveActionPerformed
        // TODO add your handling code here:
        AppWindow.ShowPanel(new leave(this, true));
    }//GEN-LAST:event_leaveActionPerformed

    private void payrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payrollActionPerformed
        // TODO add your handling code here:
        AppWindow.ShowPanel(new payroll(this, true));
    }//GEN-LAST:event_payrollActionPerformed

    private void adjusmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adjusmentActionPerformed
        // TODO add your handling code here:
        AppWindow.ShowPanel(new Adjustment(this, true));
    }//GEN-LAST:event_adjusmentActionPerformed

    private void otherdeductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherdeductionActionPerformed
        // TODO add your handling code here:
        AppWindow.ShowPanel(new otherDeduction(this, true));
    }//GEN-LAST:event_otherdeductionActionPerformed

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        // TODO add your handling code here:
        AppWindow.ShowPanel(new thirteenmonth(this, true));
    }//GEN-LAST:event_monthActionPerformed

    private void payrollreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payrollreportActionPerformed
        // TODO add your handling code here:
        AppWindow.ShowPanel(new payrollreport(this, true));
    }//GEN-LAST:event_payrollreportActionPerformed

    private void philheathreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_philheathreportActionPerformed
       // TODO add your handling code here:
       AppWindow.ShowPanel(new philhealthreport(this, true));
    }//GEN-LAST:event_philheathreportActionPerformed

    private void sssreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sssreportActionPerformed
        // TODO add your handling code here:
        AppWindow.ShowPanel(new sssreport(this, true));
    }//GEN-LAST:event_sssreportActionPerformed

    private void taxreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxreportActionPerformed
        // TODO add your handling code here:
        AppWindow.ShowPanel(new taxreport(this, true));
    }//GEN-LAST:event_taxreportActionPerformed

    private void pagibigreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagibigreportActionPerformed
        // TODO add your handling code here:
        AppWindow.ShowPanel(new pagibigreport(this, true));
    }//GEN-LAST:event_pagibigreportActionPerformed

    private void dtrreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtrreportActionPerformed
        // TODO add your handling code here:
        AppWindow.ShowPanel(new timemonitorreport(this, true));
    }//GEN-LAST:event_dtrreportActionPerformed

    private void masterlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterlistActionPerformed
        // TODO add your handling code here:
        AppWindow.ShowPanel(new mlereport(this, true));
    }//GEN-LAST:event_masterlistActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        // TODO add your handling code here:
        AppWindow.ShowPanel(new Help(this, true));
    }//GEN-LAST:event_helpActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // TODO add your handling code here:
        AppWindow.ShowPanel(new About(this, true));
    }//GEN-LAST:event_aboutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AppWindow.ShowPanel(new payroll(this, true));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        AppWindow.ShowPanel(new timemonitor(this, true));
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        AppWindow.ShowPanel(new accounts(this, true));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        AppWindow.ShowPanel(new mlereport(this, true));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        AppWindow.ShowPanel(new employee(this, true));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        AppWindow.ShowPanel(new Help(this, true));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void LogOutBtnBgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutBtnBgMouseEntered
        // TODO add your handling code here:
        LogOutBtnBg.setBackground(Color.red);
        LogOutText.setForeground(Color.BLACK);
    }//GEN-LAST:event_LogOutBtnBgMouseEntered

    private void LogOutBtnBgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutBtnBgMouseExited
        // TODO add your handling code here:
        LogOutBtnBg.setBackground(new Color(102,153,255));
        LogOutText.setForeground(Color.WHITE);
    }//GEN-LAST:event_LogOutBtnBgMouseExited

    private void LogOutBtnBgMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutBtnBgMouseReleased
        // TODO add your handling code here:
        // <editor-fold defaultstate="collapsed" desc="Logged Out Codes Process">
        AppWindow.Switch(new Login(), this);
        ProcessLog.LogOut(EmployeeInfo.getEmployee_id());
        //</editor-fold>
    }//GEN-LAST:event_LogOutBtnBgMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JLabel FullNameText;
    private javax.swing.JPanel LogOutBtnBg;
    private javax.swing.JLabel LogOutText;
    private javax.swing.JLabel LoggedAsDesc;
    private javax.swing.JMenu Maintenance;
    private javax.swing.JLabel UserLevelDescText;
    private javax.swing.JLabel UserLevelText;
    private javax.swing.JMenuItem about;
    private javax.swing.JMenuItem accounts;
    private javax.swing.JMenuItem adjusment;
    private javax.swing.JMenu contribution;
    private javax.swing.JMenuItem dtr;
    private javax.swing.JMenuItem dtrreport;
    private javax.swing.JMenuItem employee;
    private javax.swing.JMenuItem help;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem leave;
    private javax.swing.JMenuItem masterlist;
    private javax.swing.JMenuItem month;
    private javax.swing.JMenuItem otherdeduction;
    private javax.swing.JMenuItem overtime;
    private javax.swing.JMenuItem pagibig;
    private javax.swing.JMenuItem pagibigreport;
    private javax.swing.JMenuItem payroll;
    private javax.swing.JMenuItem payrollreport;
    private javax.swing.JMenuItem philhealth;
    private javax.swing.JMenuItem philheathreport;
    private javax.swing.JMenuItem position;
    private javax.swing.JTable rectable;
    private javax.swing.JMenuItem sss;
    private javax.swing.JMenuItem sssreport;
    private javax.swing.JMenuItem tax;
    private javax.swing.JMenuItem taxreport;
    private javax.swing.JMenu timemonitoring;
    private javax.swing.JMenu transaction;
    // End of variables declaration//GEN-END:variables

}