/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payroll.subwins;

import com.placeholder.PlaceHolder;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import payroll.main.db;
import payroll.secSubWins.*;
/**
 *
 * @author ASUS
 */
public class accounts extends javax.swing.JDialog {
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    PlaceHolder ph;
    int state;
    /**
     * Creates new form accounts
     */
    public accounts(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        ph = new PlaceHolder(srid, "ID");
        ph = new PlaceHolder(la, "Last Name");
        ph = new PlaceHolder(fi, "First Name");
        table();
        
    }
    public void table(){
         try{
                conn = db.db();
                pst = conn.prepareStatement("SELECT * FROM payroll_schema.account_tbl;");
                rs = pst.executeQuery();
                actable.setModel(DbUtils.resultSetToTableModel(rs));
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
                
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        actable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        srid = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        la = new javax.swing.JTextField();
        fi = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pas = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        first = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        last = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        un = new javax.swing.JTextField();
        al = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        newemp1 = new javax.swing.JButton();
        editemp1 = new javax.swing.JButton();
        cancel1 = new javax.swing.JButton();
        save1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Accounts");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        actable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Last Name", "Division"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        actable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        actable.setShowHorizontalLines(false);
        actable.setShowVerticalLines(false);
        actable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                actableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(actable);

        jLabel2.setText("Search by ID:");

        srid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        srid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sridKeyReleased(evt);
            }
        });

        jLabel35.setText("Search by Name:");

        la.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                laKeyReleased(evt);
            }
        });

        fi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fiKeyReleased(evt);
            }
        });

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll/images/refresh_update.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(srid, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton11))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(la, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fi, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(srid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(la, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Account", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jLabel5.setText("ID:");

        jLabel8.setText("Password");

        pas.setEditable(false);
        pas.setBackground(new java.awt.Color(255, 255, 255));
        pas.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        id.setEditable(false);
        id.setBackground(new java.awt.Color(255, 255, 255));
        id.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel12.setText("Access Level:");

        first.setEditable(false);
        first.setBackground(new java.awt.Color(255, 255, 255));
        first.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel26.setText("First Name:");

        jLabel25.setText("Last Name:");

        last.setEditable(false);
        last.setBackground(new java.awt.Color(255, 255, 255));
        last.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setText("Username");

        un.setEditable(false);
        un.setBackground(new java.awt.Color(255, 255, 255));
        un.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        al.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Employee", "Accountant", "Manager", "Admin" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pas)
                            .addComponent(un)
                            .addComponent(al, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 99, Short.MAX_VALUE))
                            .addComponent(first)
                            .addComponent(last))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(first, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(un, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(al, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(145, 145, 145))
        );

        jPanel9.setBackground(new java.awt.Color(59, 89, 152));

        newemp1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        newemp1.setText("New");
        newemp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newemp1ActionPerformed(evt);
            }
        });

        editemp1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        editemp1.setText("Edit");
        editemp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editemp1ActionPerformed(evt);
            }
        });

        cancel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancel1.setText("Cancel");
        cancel1.setEnabled(false);
        cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel1ActionPerformed(evt);
            }
        });

        save1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        save1.setText("Save");
        save1.setEnabled(false);
        save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newemp1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editemp1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 376, Short.MAX_VALUE)
                .addComponent(save1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cancel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newemp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editemp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(save1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actableMouseReleased
        // TODO add your handling code here:
        // <editor-fold defaultstate="collapsed" desc="Click the Table to Display Details">
        DefaultTableModel pm = (DefaultTableModel)actable.getModel();
        int sr = actable.getSelectedRow();
        id.setText(pm.getValueAt(sr, 0).toString());
        try{
            conn = db.db();
            pst = conn.prepareStatement("SELECT * FROM payroll_schema.account_tbl WHERE emp_acc_id = ?;");
            pst.setString(1, id.getText());
            rs = pst.executeQuery();

            while(rs.next()){
                first.setText(rs.getString("firstname"));
                last.setText(rs.getString("lastname"));
                un.setText(rs.getString("username"));
                pas.setText(rs.getString("password"));
                al.setSelectedItem(rs.getString("division"));
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        //</editor-fold>
    }//GEN-LAST:event_actableMouseReleased

    private void sridKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sridKeyReleased
        // TODO add your handling code here:
        // <editor-fold defaultstate="collapsed" desc="Search by Typing ID">
        if(!(evt.getKeyChar() == KeyEvent.VK_ENTER)){
        if(srid.getText().equals("")){
            id.setText("");
            first.setText("");
            last.setText("");
            un.setText("");
            pas.setText("");
            al.setSelectedIndex(0);
            try{
                conn = db.db();
                pst = conn.prepareStatement("SELECT * FROM payroll_schema.account_tbl;");
                rs = pst.executeQuery();
                actable.setModel(DbUtils.resultSetToTableModel(rs));
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
                
            }
        }else{
            try{
                conn = db.db();
                pst = conn.prepareStatement("SELECT * FROM payroll_schema.account_tbl WHERE emp_acc_id like'%"+srid.getText()+"%';");
                rs = pst.executeQuery();
                actable.setModel(DbUtils.resultSetToTableModel(rs));
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        }
        //</editor-fold>
    }//GEN-LAST:event_sridKeyReleased

    private void laKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_laKeyReleased
        // TODO add your handling code here:
        // <editor-fold defaultstate="collapsed" desc="Search by Typing the Last Name">
        if(!(evt.getKeyChar() == KeyEvent.VK_ENTER)){
        if(la.getText().equalsIgnoreCase("")){
            id.setText("");
            first.setText("");
            last.setText("");
            un.setText("");
            pas.setText("");
            al.setSelectedIndex(0);
            try{
                conn = db.db();
                pst = conn.prepareStatement("SELECT * FROM payroll_schema.account_tbl;");
                rs = pst.executeQuery();
                actable.setModel(DbUtils.resultSetToTableModel(rs));
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
                
            }
        }else{
            try{
                conn = db.db();
                pst = conn.prepareStatement("SELECT * FROM payroll_schema.account_tbl WHERE lastname like'%"+la.getText()+"%';");
                rs = pst.executeQuery();
                actable.setModel(DbUtils.resultSetToTableModel(rs));
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        }
        //</editor-fold>
    }//GEN-LAST:event_laKeyReleased

    private void fiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fiKeyReleased
        // TODO add your handling code here:
        // <editor-fold defaultstate="collapsed" desc="Search by Typing the First Name">
        if(!(evt.getKeyChar() == KeyEvent.VK_ENTER)){
            if(fi.getText().equalsIgnoreCase("")){
            id.setText("");
            first.setText("");
            last.setText("");
            un.setText("");
            pas.setText("");
            al.setSelectedIndex(0);
            try{
                conn = db.db();
                pst = conn.prepareStatement("SELECT * FROM payroll_schema.account_tbl;");
                rs = pst.executeQuery();
                actable.setModel(DbUtils.resultSetToTableModel(rs));
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
                
            }
        }else{
            try{
                conn = db.db();
                pst = conn.prepareStatement("SELECT * FROM payroll_schema.account_tbl WHERE firstname like'%"+fi.getText()+"%';");
                rs = pst.executeQuery();
                actable.setModel(DbUtils.resultSetToTableModel(rs));
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        }
        //</editor-fold>
    }//GEN-LAST:event_fiKeyReleased

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        // <editor-fold defaultstate="collapsed" desc="Refresh Accounts of Employees">
        srid.setText("");
        fi.setText("");
        la.setText("");
        id.setText("");
        first.setText("");
        last.setText("");
        un.setText("");
        pas.setText("");
        al.setSelectedIndex(0);
        ph = new PlaceHolder(srid, "ID");
        ph = new PlaceHolder(la, "Last Name");
        ph = new PlaceHolder(fi, "First Name");
        try{
                conn = db.db();
                pst = conn.prepareStatement("SELECT * FROM payroll_schema.account_tbl;");
                rs = pst.executeQuery();
                actable.setModel(DbUtils.resultSetToTableModel(rs));
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        //</editor-fold>
    }//GEN-LAST:event_jButton11ActionPerformed

    private void newemp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newemp1ActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Do you want to add a account?","Add Record",JOptionPane.YES_NO_OPTION);
        if(p == 0){
            try{
                conn = db.db();
                pst = conn.prepareStatement("SELECT * FROM payroll_schema.account_tbl  ORDER BY emp_acc_id DESC Limit 1;");
                rs = pst.executeQuery();
                
                while(rs.next()){
                 int recentid  = rs.getInt("emp_acc_id");
                 int newid = recentid + 1;
                 id.setText(""+newid);
                }
            }
            catch(Exception e){JOptionPane.showMessageDialog(null, e);}
            state = 1;
            id.setEditable(true);
            last.setEditable(true);
            first.setEditable(true);
            un.setEditable(true);
            pas.setEditable(true);
            srid.setEditable(false);
            la.setEditable(false);
            fi.setEditable(false);
            save1.setEnabled(true);
            cancel1.setEnabled(true);
            newemp1.setEnabled(false);
            editemp1.setEnabled(false);
            jButton11.setEnabled(false);
            actable.setEnabled(false);
            
            last.setText("");
            first.setText("");
            un.setText("");
            pas.setText("");
            al.setSelectedIndex(0);
        }
    }//GEN-LAST:event_newemp1ActionPerformed

    private void editemp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editemp1ActionPerformed
        // TODO add your handling code here:
        if(id.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please select account to update");
        }else{
            int p = JOptionPane.showConfirmDialog(null, "Do you want to update a account?","Update Record",JOptionPane.YES_NO_OPTION);
            if(p == 0){
                state =2;
                id.setEditable(true);
                last.setEditable(true);
                first.setEditable(true);
                un.setEditable(true);
                pas.setEditable(true);
                srid.setEditable(false);
                la.setEditable(false);
                fi.setEditable(false);
                save1.setEnabled(true);
                cancel1.setEnabled(true);
                newemp1.setEnabled(false);
                editemp1.setEnabled(false);
                jButton11.setEnabled(false);
                actable.setEnabled(false);
            }
        }
    }//GEN-LAST:event_editemp1ActionPerformed

    private void cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel1ActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Do you want to cancel?","Caution",JOptionPane.YES_NO_OPTION);
        if(p == 0){
            id.setEditable(false);
            last.setEditable(false);
            first.setEditable(false);
            un.setEditable(false);
            pas.setEditable(false);
            srid.setEditable(true);
            la.setEditable(true);
            fi.setEditable(true);
            jButton11.setEnabled(true);
            actable.setEnabled(true);
            save1.setEnabled(false);
            cancel1.setEnabled(false);
            newemp1.setEnabled(true);
            editemp1.setEnabled(true);
            last.setText("");
            first.setText("");
            un.setText("");
            pas.setText("");
            id.setText("");
            al.setSelectedIndex(0);
        }
    }//GEN-LAST:event_cancel1ActionPerformed

    private void save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save1ActionPerformed
        // TODO add your handling code here:
        if(state == 1){
            int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to add this account?","Add Record",JOptionPane.YES_NO_OPTION);
            if(p == 0){
                if(id.getText().equals("")){
                    JOptionPane.showMessageDialog(null,"The id is empty");
                }
                if(un.getText().equals("")){
                    JOptionPane.showMessageDialog(null,"The user name is empty");
                }
                if(pas.getText().equals("")){
                    JOptionPane.showMessageDialog(null,"The password is empty");
                }
                if(al.getSelectedItem().toString().equals("Select")){
                    JOptionPane.showMessageDialog(null,"The access level is not selected");
                }
                if(!id.getText().equals("") && !un.getText().equals("") && !pas.getText().equals("") && !al.getSelectedItem().toString().equals("Select")){
                    
                    try{
                        conn = db.db();
                        pst = conn.prepareStatement("INSERT INTO payroll_schema.account_tbl "
                            + "VALUES (?,?,?,?,?,?);");
                        pst.setString(1, id.getText());
                        pst.setString(4, first.getText());
                        pst.setString(5, last.getText());
                        pst.setString(2, un.getText());
                        pst.setString(3, pas.getText());
                        pst.setString(6, al.getSelectedItem().toString());
                        pst.execute();
                    }
                    catch(Exception e){
                        JOptionPane.showMessageDialog(null, e);
                    }
                    JOptionPane.showMessageDialog(null, "Added Successfully");

                    table();
                    id.setEditable(false);
                    last.setEditable(false);
                    first.setEditable(false);
                    un.setEditable(false);
                    pas.setEditable(false);
                    srid.setEditable(true);
                    la.setEditable(false);
                    fi.setEditable(false);
                    jButton11.setEnabled(true);
                    actable.setEnabled(true);
                    save1.setEnabled(false);
                    cancel1.setEnabled(false);
                    newemp1.setEnabled(true);
                    editemp1.setEnabled(true);
                }
            }
        }else if(state == 2){
            int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to update the detail of this account?","Update Record",JOptionPane.YES_NO_OPTION);
            if(p == 0){
                if(id.getText().equals("")){
                    JOptionPane.showMessageDialog(null,"The id is empty");
                }
                if(un.getText().equals("")){
                    JOptionPane.showMessageDialog(null,"The user name is empty");
                }
                if(pas.getText().equals("")){
                    JOptionPane.showMessageDialog(null,"The password is empty");
                }
                if(al.getSelectedItem().toString().equals("Select")){
                    JOptionPane.showMessageDialog(null,"The access level is not selected");
                }
                if(!id.getText().equals("") && !un.getText().equals("") && !pas.getText().equals("") && !al.getSelectedItem().toString().equals("Select")){
                    try{
                        conn = db.db();
                        pst = conn.prepareStatement("UPDATE payroll_schema.account_tbl SET firstname = ?, "
                            + "lastname = ?, username = ?, password = ?,  division = ? WHERE emp_acc_id = ?");
                        pst.setString(6, id.getText());
                        pst.setString(1, first.getText());
                        pst.setString(2, last.getText());
                        pst.setString(3, un.getText());
                        pst.setString(4, pas.getText());
                        pst.setString(5, al.getSelectedItem().toString());
                        pst.execute();
                    }
                    catch(Exception e){
                        JOptionPane.showMessageDialog(null, e);
                    }
                    JOptionPane.showMessageDialog(null, "Updated Successfully");
                    table();
                    id.setEditable(false);
                    last.setEditable(false);
                    first.setEditable(false);
                    un.setEditable(false);
                    pas.setEditable(false);
                    srid.setEditable(true);
                    la.setEditable(false);
                    fi.setEditable(false);
                    jButton11.setEnabled(true);
                    actable.setEnabled(true);
                    save1.setEnabled(false);
                    cancel1.setEnabled(false);
                    newemp1.setEnabled(true);
                    editemp1.setEnabled(true);
                }
            }
        }
    }//GEN-LAST:event_save1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(accounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(accounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(accounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                accounts dialog = new accounts(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable actable;
    private javax.swing.JComboBox<String> al;
    private javax.swing.JButton cancel1;
    private javax.swing.JButton editemp1;
    private javax.swing.JTextField fi;
    private javax.swing.JTextField first;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField la;
    private javax.swing.JTextField last;
    private javax.swing.JButton newemp1;
    private javax.swing.JTextField pas;
    private javax.swing.JButton save1;
    private javax.swing.JTextField srid;
    private javax.swing.JTextField un;
    // End of variables declaration//GEN-END:variables
}
