/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payroll.subwins;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import payroll.helppanel.*;

/**
 *
 * @author Hp
 */
public class Help extends javax.swing.JDialog {
    GridBagLayout layout = new GridBagLayout();
    howtologin howtologin =new howtologin();
    howtoaddemployee addemployee = new howtoaddemployee();
    howtoremoveemployee removeemployee =new howtoremoveemployee();
    howtoupdateemploye updateemployee =new howtoupdateemploye();
    howtoaddaccount addaccount =new howtoaddaccount();
    howtoupdateaccount updateaccount =new howtoupdateaccount();
    howtoremoveaccount removeaccount =new howtoremoveaccount();
    howtoupdatetimemonitoring updatetimemonitoring = new howtoupdatetimemonitoring();
    howtoremovetimemonitoring removetimemonitoring = new howtoremovetimemonitoring();
    howtoaddovertime addovertime = new howtoaddovertime();
    howtoupdateovertime updateovertime = new howtoupdateovertime();
    howtoremoveovertime removeovertime = new howtoremoveovertime();
    howtoaddadjustmentrecord addadjustmentrecord = new howtoaddadjustmentrecord();
    howtoupdateadjustmentrecord updateadjustmentrecord = new howtoupdateadjustmentrecord();
    howtoremoveadjustmentrecord removeadjustmentrecord = new howtoremoveadjustmentrecord();
    howtoadddeduction adddeduction= new howtoadddeduction();
    howtoupdatededuction updatededuction= new howtoupdatededuction();
    Howtoremovededuction removededuction= new Howtoremovededuction();
    

    /**
     * Creates new form Help
     */
    public Help(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        dp.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        dp.add(howtologin, c);
        c.gridx = 0;
        c.gridy = 0;
        howtologin.setVisible(false);
        dp.add(addemployee, c);
        c.gridx = 0;
        c.gridy = 0;
        addemployee.setVisible(false);
         dp.add(updateemployee, c);
        c.gridx = 0;
        c.gridy = 0;
        updateemployee.setVisible(false);
        dp.add(removeemployee, c);
        c.gridx = 0;
        c.gridy = 0;
        removeemployee.setVisible(false);
        dp.add(addaccount, c);
        c.gridx = 0;
        c.gridy = 0;
        addaccount.setVisible(false);
        dp.add(removeaccount, c);
        c.gridx = 0;
        c.gridy = 0;
        removeaccount.setVisible(false);
        dp.add(updateaccount, c);
        c.gridx = 0;
        c.gridy = 0;
        updateaccount.setVisible(false);
        dp.add(updatetimemonitoring, c);
        c.gridx = 0;
        c.gridy = 0;
        updatetimemonitoring.setVisible(false);
        dp.add(removetimemonitoring, c);
        c.gridx = 0;
        c.gridy = 0;
        removetimemonitoring.setVisible(false);
        dp.add(addovertime, c);
        c.gridx = 0;
        c.gridy = 0;
        addovertime.setVisible(false);
        dp.add(updateovertime, c);
        c.gridx = 0;
        c.gridy = 0;
        updateovertime.setVisible(false);
        dp.add(removeovertime, c);
        c.gridx = 0;
        c.gridy = 0;
        removeovertime.setVisible(false);
        dp.add(addadjustmentrecord, c);
        c.gridx = 0;
        c.gridy = 0;
        addadjustmentrecord.setVisible(false);
        dp.add(updateadjustmentrecord, c);
        c.gridx = 0;
        c.gridy = 0;
        updateadjustmentrecord.setVisible(false);
        dp.add(removeadjustmentrecord, c);
        c.gridx = 0;
        c.gridy = 0;
        removeadjustmentrecord.setVisible(false);
        dp.add(adddeduction, c);
        c.gridx = 0;
        c.gridy = 0;
        adddeduction.setVisible(false);
        dp.add(updatededuction, c);
        c.gridx = 0;
        c.gridy = 0;
        updatededuction.setVisible(false);
        dp.add(removededuction, c);
        c.gridx = 0;
        c.gridy = 0;
        removededuction.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        dp = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Help");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("How  to Login");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("How  to add Employee");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("How to remove Employee");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("How to update Employee");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("How to add  account");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("How to Update Account");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("How to Remove Account");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("How to Update Time Monitoring");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("How to Remove Time Monitoring");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("How to add over time");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("How to update over time");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("How to remove over time");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("How to add adjustment record");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("How to update adjustment record");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        dp.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout dpLayout = new javax.swing.GroupLayout(dp);
        dp.setLayout(dpLayout);
        dpLayout.setHorizontalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );
        dpLayout.setVerticalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("How to remove adjustment record");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("How to add deduction");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("How to update deduction");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("How to remove deduction");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap(33, Short.MAX_VALUE))
            .addComponent(dp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        howtologin.setVisible(true);
        removeemployee.setVisible(false);
        addemployee.setVisible(false);
        updateemployee.setVisible(false);
        addaccount.setVisible(false);
        updateaccount.setVisible(false);
        removeaccount.setVisible(false);
        updatetimemonitoring.setVisible(false);
        removetimemonitoring.setVisible(false);
        addovertime.setVisible(false);
        updateovertime.setVisible(false);
        removeovertime.setVisible(false);
        addadjustmentrecord.setVisible(false);
        updateadjustmentrecord.setVisible(false);
        removeadjustmentrecord.setVisible(false);
        adddeduction.setVisible(false);
        updatededuction.setVisible(false);
        removededuction.setVisible(false);
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        
        howtologin.setVisible(false);
        removeemployee.setVisible(false);
        addemployee.setVisible(true);
        updateemployee.setVisible(false);
        addaccount.setVisible(false);
        updateaccount.setVisible(false);
        removeaccount.setVisible(false);
        updatetimemonitoring.setVisible(false);
        removetimemonitoring.setVisible(false);
        addovertime.setVisible(false);
        updateovertime.setVisible(false);
        removeovertime.setVisible(false);
        addadjustmentrecord.setVisible(false);
        updateadjustmentrecord.setVisible(false);
        removeadjustmentrecord.setVisible(false);
        adddeduction.setVisible(false);
        updatededuction.setVisible(false);
        removededuction.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked
 
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        howtologin.setVisible(false);
        removeemployee.setVisible(true);
        addemployee.setVisible(false);
        updateemployee.setVisible(false);
        addaccount.setVisible(false);
        updateaccount.setVisible(false);
        removeaccount.setVisible(false);
        updatetimemonitoring.setVisible(false);
        removetimemonitoring.setVisible(false);
        addovertime.setVisible(false);
        updateovertime.setVisible(false);
        removeovertime.setVisible(false);
        addadjustmentrecord.setVisible(false);
        updateadjustmentrecord.setVisible(false);
        removeadjustmentrecord.setVisible(false);
        adddeduction.setVisible(false);
        updatededuction.setVisible(false);
        removededuction.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        howtologin.setVisible(false);
        removeemployee.setVisible(false);
        addemployee.setVisible(false);
        updateemployee.setVisible(true);
        addaccount.setVisible(false);
        updateaccount.setVisible(false);
        removeaccount.setVisible(false);
        updatetimemonitoring.setVisible(false);
        removetimemonitoring.setVisible(false);
        addovertime.setVisible(false);
        updateovertime.setVisible(false);
        removeovertime.setVisible(false);
        addadjustmentrecord.setVisible(false);
        updateadjustmentrecord.setVisible(false);
        removeadjustmentrecord.setVisible(false);
        adddeduction.setVisible(false);
        updatededuction.setVisible(false);
        removededuction.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        howtologin.setVisible(false);
        removeemployee.setVisible(false);
        addemployee.setVisible(false);
        updateemployee.setVisible(false);
         addaccount.setVisible(true);
         updateaccount.setVisible(false);
         removeaccount.setVisible(false);
         updatetimemonitoring.setVisible(false);
         removetimemonitoring.setVisible(false);
         addovertime.setVisible(false);
         updateovertime.setVisible(false);
         removeovertime.setVisible(false);
         addadjustmentrecord.setVisible(false);
         updateadjustmentrecord.setVisible(false);
         removeadjustmentrecord.setVisible(false);
         adddeduction.setVisible(false);
         updatededuction.setVisible(false);
         removededuction.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        howtologin.setVisible(false);
        removeemployee.setVisible(false);
        addemployee.setVisible(false);
        updateemployee.setVisible(false);
         addaccount.setVisible(false);
         updateaccount.setVisible(true);
         removeaccount.setVisible(false);
         updatetimemonitoring.setVisible(false);
         removetimemonitoring.setVisible(false);
         addovertime.setVisible(false);
         updateovertime.setVisible(false);
         removeovertime.setVisible(false);
         addadjustmentrecord.setVisible(false);
         updateadjustmentrecord.setVisible(false);
         removeadjustmentrecord.setVisible(false);
         adddeduction.setVisible(false);
         updatededuction.setVisible(false);
         removededuction.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        howtologin.setVisible(false);
        removeemployee.setVisible(false);
        addemployee.setVisible(false);
        updateemployee.setVisible(false);
        addaccount.setVisible(false);
        updateaccount.setVisible(false);
        removeaccount.setVisible(true);
        updatetimemonitoring.setVisible(false);
        removetimemonitoring.setVisible(false);
        addovertime.setVisible(false);
        updateovertime.setVisible(false);
        removeovertime.setVisible(false);
        addadjustmentrecord.setVisible(false);
        updateadjustmentrecord.setVisible(false);
        removeadjustmentrecord.setVisible(false);
        adddeduction.setVisible(false);
        updatededuction.setVisible(false);
        removededuction.setVisible(false);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
         howtologin.setVisible(false);
        removeemployee.setVisible(false);
        addemployee.setVisible(false);
        updateemployee.setVisible(false);
        addaccount.setVisible(false);
        updateaccount.setVisible(false);
        removeaccount.setVisible(false);
        updatetimemonitoring.setVisible(true);
        removetimemonitoring.setVisible(false);
        addovertime.setVisible(false);
        updateovertime.setVisible(false);
        removeovertime.setVisible(false);
        addadjustmentrecord.setVisible(false);
        updateadjustmentrecord.setVisible(false);
        removeadjustmentrecord.setVisible(false);
        adddeduction.setVisible(false);
        updatededuction.setVisible(false);
        removededuction.setVisible(false);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
          howtologin.setVisible(false);
        removeemployee.setVisible(false);
        addemployee.setVisible(false);
        updateemployee.setVisible(false);
        addaccount.setVisible(false);
        updateaccount.setVisible(false);
        removeaccount.setVisible(false);
        updatetimemonitoring.setVisible(false);
        removetimemonitoring.setVisible(true);
        addovertime.setVisible(false);
        updateovertime.setVisible(false);
        removeovertime.setVisible(false);
        addadjustmentrecord.setVisible(false);
        updateadjustmentrecord.setVisible(false);
        removeadjustmentrecord.setVisible(false);
        adddeduction.setVisible(false);
        updatededuction.setVisible(false);
        removededuction.setVisible(false);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        howtologin.setVisible(false);
        removeemployee.setVisible(false);
        addemployee.setVisible(false);
        updateemployee.setVisible(false);
        addaccount.setVisible(false);
        updateaccount.setVisible(false);
        removeaccount.setVisible(false);
        updatetimemonitoring.setVisible(false);
        removetimemonitoring.setVisible(false);
        addovertime.setVisible(true);
        updateovertime.setVisible(false);
        removeovertime.setVisible(false);
        addadjustmentrecord.setVisible(false);
        updateadjustmentrecord.setVisible(false);
        removeadjustmentrecord.setVisible(false);
        adddeduction.setVisible(false);
        updatededuction.setVisible(false);
        removededuction.setVisible(false);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
         howtologin.setVisible(false);
        removeemployee.setVisible(false);
        addemployee.setVisible(false);
        updateemployee.setVisible(false);
        addaccount.setVisible(false);
        updateaccount.setVisible(false);
        removeaccount.setVisible(false);
        updatetimemonitoring.setVisible(false);
        removetimemonitoring.setVisible(false);
        addovertime.setVisible(false);
        updateovertime.setVisible(true);
        removeovertime.setVisible(false);
        addadjustmentrecord.setVisible(false);
        updateadjustmentrecord.setVisible(false);
        removeadjustmentrecord.setVisible(false);
        adddeduction.setVisible(false);
        updatededuction.setVisible(false);
        removededuction.setVisible(false);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        howtologin.setVisible(false);
        removeemployee.setVisible(false);
        addemployee.setVisible(false);
        updateemployee.setVisible(false);
        addaccount.setVisible(false);
        updateaccount.setVisible(false);
        removeaccount.setVisible(false);
        updatetimemonitoring.setVisible(false);
        removetimemonitoring.setVisible(false);
        addovertime.setVisible(false);
        updateovertime.setVisible(false);
        removeovertime.setVisible(true);
        addadjustmentrecord.setVisible(false);
        updateadjustmentrecord.setVisible(false);
        removeadjustmentrecord.setVisible(false);
        adddeduction.setVisible(false);
        updatededuction.setVisible(false);
        removededuction.setVisible(false);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        howtologin.setVisible(false);
        removeemployee.setVisible(false);
        addemployee.setVisible(false);
        updateemployee.setVisible(false);
        addaccount.setVisible(false);
        updateaccount.setVisible(false);
        removeaccount.setVisible(false);
        updatetimemonitoring.setVisible(false);
        removetimemonitoring.setVisible(false);
        addovertime.setVisible(false);
        updateovertime.setVisible(false);
        removeovertime.setVisible(false);
        addadjustmentrecord.setVisible(true);
        updateadjustmentrecord.setVisible(false);
        removeadjustmentrecord.setVisible(false);
        adddeduction.setVisible(false);
        updatededuction.setVisible(false);
        removededuction.setVisible(false);
                                      
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        howtologin.setVisible(false);
        removeemployee.setVisible(false);
        addemployee.setVisible(false);
        updateemployee.setVisible(false);
        addaccount.setVisible(false);
        updateaccount.setVisible(false);
        removeaccount.setVisible(false);
        updatetimemonitoring.setVisible(false);
        removetimemonitoring.setVisible(false);
        addovertime.setVisible(false);
        updateovertime.setVisible(false);
        removeovertime.setVisible(false);
        addadjustmentrecord.setVisible(false);
        updateadjustmentrecord.setVisible(true);
        removeadjustmentrecord.setVisible(false);
        adddeduction.setVisible(false);
        updatededuction.setVisible(false);
        removededuction.setVisible(false);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        howtologin.setVisible(false);
        removeemployee.setVisible(false);
        addemployee.setVisible(false);
        updateemployee.setVisible(false);
        addaccount.setVisible(false);
        updateaccount.setVisible(false);
        removeaccount.setVisible(false);
        updatetimemonitoring.setVisible(false);
        removetimemonitoring.setVisible(false);
        addovertime.setVisible(false);
        updateovertime.setVisible(false);
        removeovertime.setVisible(false);
        addadjustmentrecord.setVisible(false);
        updateadjustmentrecord.setVisible(false);
        removeadjustmentrecord.setVisible(true);
        adddeduction.setVisible(false);
        updatededuction.setVisible(false);
        removededuction.setVisible(false);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        howtologin.setVisible(false);
        removeemployee.setVisible(false);
        addemployee.setVisible(false);
        updateemployee.setVisible(false);
        addaccount.setVisible(false);
        updateaccount.setVisible(false);
        removeaccount.setVisible(false);
        updatetimemonitoring.setVisible(false);
        removetimemonitoring.setVisible(false);
        addovertime.setVisible(false);
        updateovertime.setVisible(false);
        removeovertime.setVisible(false);
        addadjustmentrecord.setVisible(false);
        updateadjustmentrecord.setVisible(false);
        removeadjustmentrecord.setVisible(false);
        adddeduction.setVisible(true);
        updatededuction.setVisible(false);
        removededuction.setVisible(false);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
             howtologin.setVisible(false);
        removeemployee.setVisible(false);
        addemployee.setVisible(false);
        updateemployee.setVisible(false);
        addaccount.setVisible(false);
        updateaccount.setVisible(false);
        removeaccount.setVisible(false);
        updatetimemonitoring.setVisible(false);
        removetimemonitoring.setVisible(false);
        addovertime.setVisible(false);
        updateovertime.setVisible(false);
        removeovertime.setVisible(false);
        addadjustmentrecord.setVisible(false);
        updateadjustmentrecord.setVisible(false);
        removeadjustmentrecord.setVisible(false);
        adddeduction.setVisible(false);
        updatededuction.setVisible(false);
        removededuction.setVisible(true);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Help dialog = new Help(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
