/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payroll.subwins;

import com.placeholder.PlaceHolder;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import net.proteanit.sql.DbUtils;
import payroll.main.db;
import payroll.secSubWins.updateTimeMoni;

/**
 *
 * @author ASUS
 */
public class timemonitor extends javax.swing.JDialog {
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    PlaceHolder ph;
    int state;
    String status;
    int timeHour;
    /**
     * Creates new form timemonitor
     */
    public timemonitor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        table();
        ph = new PlaceHolder(srid, "ID");
        ph = new PlaceHolder(srln, "Last Name");
        ph = new PlaceHolder(srfn, "First Name");
    }
    public void table(){
        try{
            conn = db.db();
            pst = conn.prepareStatement("SELECT * FROM payroll_schema.timemonitor_tbl ORDER BY date_in DESC");
            rs = pst.executeQuery();
            rectable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        id = new javax.swing.JTextField();
        fn = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ln = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ti = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        to = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        dtout = new javax.swing.JTextField();
        dtin = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        li = new javax.swing.JCheckBox();
        lo = new javax.swing.JCheckBox();
        twh = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rectable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        srid = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        srln = new javax.swing.JTextField();
        srfn = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        newemp1 = new javax.swing.JButton();
        editemp1 = new javax.swing.JButton();
        save1 = new javax.swing.JButton();
        cancel1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Time Monitor");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Time Monitor Record", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        id.setEditable(false);
        id.setBackground(new java.awt.Color(255, 255, 255));
        id.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idKeyReleased(evt);
            }
        });

        fn.setEditable(false);
        fn.setBackground(new java.awt.Color(255, 255, 255));
        fn.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel26.setText("First Name:");

        jLabel25.setText("Last Name:");

        ln.setEditable(false);
        ln.setBackground(new java.awt.Color(255, 255, 255));
        ln.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnActionPerformed(evt);
            }
        });

        jLabel12.setText("Time In");

        ti.setEditable(false);
        ti.setBackground(new java.awt.Color(255, 255, 255));
        ti.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setText("ID:");

        jLabel13.setText("Time Out");

        to.setEditable(false);
        to.setBackground(new java.awt.Color(255, 255, 255));
        to.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel14.setText("to");

        jLabel15.setText("Date In");

        jLabel16.setText("Date Out");

        dtout.setEditable(false);
        dtout.setBackground(new java.awt.Color(255, 255, 255));
        dtout.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dtin.setEditable(false);
        dtin.setBackground(new java.awt.Color(255, 255, 255));
        dtin.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel17.setText("to");

        jLabel1.setText("hh:mm:ss");

        jLabel3.setText("mm/dd/yyyy");

        li.setBackground(new java.awt.Color(255, 255, 255));
        li.setText("Logged In");
        li.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liActionPerformed(evt);
            }
        });

        lo.setBackground(new java.awt.Color(255, 255, 255));
        lo.setText("Logged Out");
        lo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loActionPerformed(evt);
            }
        });

        twh.setEditable(false);
        twh.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Time Work Hours:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ln, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(fn)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(5, 5, 5))
                                    .addComponent(dtout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dtin, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(li)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(to, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                        .addComponent(ti)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel16)
                                        .addGap(71, 71, 71))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(lo)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(42, 42, 42))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(twh, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(ln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dtin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(ti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(dtout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(li)
                    .addComponent(lo))
                .addGap(44, 44, 44))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DailyTimeRecord", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        rectable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Last Name", "Date In", "Time In", "Date Out", "Time Out", "Status"
            }
        ));
        rectable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        rectable.setShowHorizontalLines(false);
        rectable.setShowVerticalLines(false);
        rectable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rectableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(rectable);

        jLabel4.setText("Search by ID:");

        srid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        srid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sridKeyReleased(evt);
            }
        });

        jLabel35.setText("Search by Name:");

        srln.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        srln.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srlnKeyReleased(evt);
            }
        });

        srfn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        srfn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srfnKeyReleased(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll/images/refresh_update.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel35)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(srln, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(srfn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(srid, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(srid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srfn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(59, 89, 152));

        newemp1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        newemp1.setText("New");
        newemp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newemp1ActionPerformed(evt);
            }
        });

        editemp1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        editemp1.setText("Edit");
        editemp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editemp1ActionPerformed(evt);
            }
        });

        save1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        save1.setText("Save");
        save1.setEnabled(false);
        save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save1ActionPerformed(evt);
            }
        });

        cancel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancel1.setText("Cancel");
        cancel1.setEnabled(false);
        cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newemp1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editemp1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(save1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(save1)
                        .addComponent(cancel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(newemp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editemp1)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnActionPerformed

    private void rectableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rectableMouseReleased
        // TODO add your handling code here:
        // <editor-fold defaultstate="collapsed" desc="Display Details of DTR by Clicking the Table">
        DefaultTableModel pm = (DefaultTableModel)rectable.getModel();
        int sr = rectable.getSelectedRow();

        ln.setText(pm.getValueAt(sr, 1).toString());
        fn.setText(pm.getValueAt(sr, 2).toString());
        id.setText(pm.getValueAt(sr, 0).toString());
        dtin.setText(pm.getValueAt(sr, 3).toString());
        ti.setText(pm.getValueAt(sr, 4).toString());
        dtout.setText(pm.getValueAt(sr, 5).toString());
        to.setText(pm.getValueAt(sr, 6).toString());
        twh.setText(pm.getValueAt(sr, 8).toString());
        
        String b = pm.getValueAt(sr, 7).toString();
        if(b.equals("Logged In")){
            
            li.setSelected(true);
            lo.setSelected(false);
        }else
        if(b.equals("Logged Out")){
            
            lo.setSelected(true);
            li.setSelected(false);
        }
        
        //</editor-fold>
    }//GEN-LAST:event_rectableMouseReleased

    private void sridKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sridKeyReleased
        // TODO add your handling code here:
        // <editor-fold defaultstate="collapsed" desc="Display Details of DTR by Typing the ID">
        if(!(evt.getKeyChar() == KeyEvent.VK_ENTER)){
        if(srid.getText().equals("")){
            table();
        }else{
            try{
            conn = db.db();
            pst = conn.prepareStatement("SELECT * FROM payroll_schema.timemonitor_tbl WHERE id like'%"+srid.getText()+"%' ORDER BY date_in DESC; ");
            rs = pst.executeQuery();
            rectable.setModel(DbUtils.resultSetToTableModel(rs));
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        }
        //</editor-fold>
    }//GEN-LAST:event_sridKeyReleased

    private void srlnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srlnKeyReleased
        // TODO add your handling code here:
        // <editor-fold defaultstate="collapsed" desc="Display Details of DTR by Typing the Last Name">
        if(!(evt.getKeyChar() == KeyEvent.VK_ENTER)){
        if(srln.getText().equalsIgnoreCase("")){
        table();
        }else{
            try{
            conn = db.db();
            pst = conn.prepareStatement("SELECT * FROM payroll_schema.timemonitor_tbl WHERE lastname like'%"+srln.getText()+"%' ORDER BY date_in DESC; ");
            rs = pst.executeQuery();
            rectable.setModel(DbUtils.resultSetToTableModel(rs));
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        }
        //</editor-fold>
    }//GEN-LAST:event_srlnKeyReleased

    private void srfnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srfnKeyReleased
        // TODO add your handling code here:
        // <editor-fold defaultstate="collapsed" desc="Display Details of DTR by Typing the First Name">
        if(!(evt.getKeyChar() == KeyEvent.VK_ENTER)){
        if(srfn.getText().equalsIgnoreCase("")){
        table();
        }else{
            try{
            conn = db.db();
            pst = conn.prepareStatement("SELECT * FROM payroll_schema.timemonitor_tbl WHERE firstname like'%"+srfn.getText()+"%' ORDER BY date_in DESC; ");
            rs = pst.executeQuery();
            rectable.setModel(DbUtils.resultSetToTableModel(rs));
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        }
        //</editor-fold>
    }//GEN-LAST:event_srfnKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // <editor-fold defaultstate="collapsed" desc="Refresh Details of DTR">
        id.setText("");
        fn.setText("");
        ln.setText("");
        dtin.setText("");
        dtout.setText("");
        ti.setText("");
        to.setText("");
        srid.setText("");
        srln.setText("");
        srfn.setText("");
        ph = new PlaceHolder(srid, "ID");
        ph = new PlaceHolder(srln, "Last Name");
        ph = new PlaceHolder(srfn, "First Name");
        try{
            conn = db.db();
            pst = conn.prepareStatement("SELECT * FROM payroll_schema.timemonitor_tbl ORDER BY date_in DESC");
            rs = pst.executeQuery();
            rectable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        //</editor-fold>
    }//GEN-LAST:event_jButton4ActionPerformed

    private void newemp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newemp1ActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Do you want to add a reocrd?","Add Record",JOptionPane.YES_NO_OPTION);
        if(p == 0){
            state = 1;
            id.setEditable(true);
            fn.setEditable(true);
            ln.setEditable(true);
            to.setEditable(true);
            ti.setEditable(true);
            dtin.setEditable(true);
            dtout.setEditable(true);
            twh.setEditable(true);
            rectable.setEnabled(false);
            srid.setEditable(false);
            srfn.setEditable(false);
            srln.setEditable(false);
            jButton4.setEnabled(false);
            save1.setEnabled(true);
            cancel1.setEnabled(true);
            newemp1.setEnabled(false);
            editemp1.setEnabled(false);
            id.setText("");
            fn.setText("");
            ln.setText("");
            to.setText("");
            ti.setText("");
            twh.setText("");
            srid.setText("");
            srfn.setText("");
            srln.setText("");
            ph = new PlaceHolder(srid, "ID");
            ph = new PlaceHolder(srln, "Last Name");
            ph = new PlaceHolder(srfn, "First Name");
            java.util.Date cd = GregorianCalendar.getInstance().getTime();
            SimpleDateFormat df = new SimpleDateFormat("MM/dd/yyyy");
            String dateString = df.format(cd);
            dtin.setText(dateString);
            dtout.setText(dateString);
        }
    }//GEN-LAST:event_newemp1ActionPerformed

    private void editemp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editemp1ActionPerformed
        // TODO add your handling code here:
        if(id.getText().equals("") && fn.getText().equals("") && ln.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please select record to update");
        }else{
            int p = JOptionPane.showConfirmDialog(null, "Do you want to update this record?","Update Record",JOptionPane.YES_NO_OPTION);
            if(p == 0){
                state =2;
                id.setEditable(true);
                fn.setEditable(true);
                ln.setEditable(true);
                to.setEditable(true);
                ti.setEditable(true);
                dtin.setEditable(true);
                dtout.setEditable(true);
                twh.setEditable(true);
                rectable.setEnabled(false);
                srid.setEditable(false);
                srfn.setEditable(false);
                srln.setEditable(false);
                jButton4.setEnabled(false);
                save1.setEnabled(true);
                cancel1.setEnabled(true);
                newemp1.setEnabled(false);
            editemp1.setEnabled(false);
                srid.setText("");
                srfn.setText("");
                srln.setText("");
                ph = new PlaceHolder(srid, "ID");
                ph = new PlaceHolder(srln, "Last Name");
                ph = new PlaceHolder(srfn, "First Name");
            }
        }
    }//GEN-LAST:event_editemp1ActionPerformed

    private void liActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liActionPerformed
        // TODO add your handling code here:
        li.setSelected(true);
        lo.setSelected(false);
        status = "Logged In";
    }//GEN-LAST:event_liActionPerformed

    private void loActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loActionPerformed
        // TODO add your handling code here:
        lo.setSelected(true);
        li.setSelected(false);
        status = "Logged Out";
    }//GEN-LAST:event_loActionPerformed

    private void save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save1ActionPerformed
        // TODO add your handling code here:
        if(state == 1){
            int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to add the status of this employee?","Add Record",JOptionPane.YES_NO_OPTION);
            if(p == 0){
                
                String hour = ti.getText().substring(0, 2);//first
                String min = ti.getText().substring(3, 5);//first

                String hour1 = to.getText().substring(0, 2);//second
                String min1 = to.getText().substring(3, 5);//second

                Integer hours = Integer.parseInt(hour);//first
                Integer mins = Integer.parseInt(min);//first

                Integer hours1 = Integer.parseInt(hour1);//second
                Integer mins1 = Integer.parseInt(min1);//second
                if(hours == hours1){
                        int timemin = mins1 -mins ;
                        if(timemin < 60){
                           timeHour = 1;
                        }
                     }else if(hours < hours1 && mins1 <= 30){
                         timeHour = hours1 - hours;
                     }else if(hours < hours1 && mins1 > 30){
                         timeHour = hours1 - hours + 1;
                     }else if(hours1 > 0 && hours1 < hours && mins1 > 30){
                         timeHour =  ((24 - hours) + hours1)+1;
                     }else if(hours1 > 0 && hours1 < hours && mins1 < 30){
                         timeHour =  (24 - hours) + hours1;
                     }
                    try{
                        conn = db.db();
                        pst = conn.prepareStatement("insert into payroll_schema.overtime_tbl values (?,?,?,?,?,?,?,?,?,?);");
                        pst.setString(1, id.getText());
                        pst.setString(2, ln.getText());
                        pst.setString(3, fn.getText());
                        pst.setString(4, String.valueOf(timeHour));
                        pst.setString(5, "No Validation");
                        pst.setString(6, ti.getText());
                        pst.setString(7, to.getText());
                        pst.setString(8, dtin.getText());
                        pst.setString(9, "Not yet recorded");
                        pst.setString(10, "No Validation");
                        pst.execute();
                    }
                    catch(Exception e){
                        JOptionPane.showMessageDialog(null, e);
                    }
                    try{
                    conn = db.db();
                    pst = conn.prepareStatement("INSERT INTO payroll_schema.timemonitor_tbl values (?,?,?,?,?,?,?,?,?)");
                    pst.setString(1, id.getText());
                    pst.setString(2, ln.getText());
                    pst.setString(3, fn.getText());
                    pst.setString(4, dtin.getText());
                    pst.setString(5, ti.getText());
                    pst.setString(6, dtout.getText());
                    pst.setString(7, to.getText());
                    pst.setString(8, status);
                    pst.setString(9, String.valueOf(timeHour));
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Adding Success");
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
                id.setEditable(false);
                    fn.setEditable(false);
                    ln.setEditable(false);
                    to.setEditable(false);
                    ti.setEditable(false);
                    dtin.setEditable(false);
                    dtout.setEditable(false);
                    twh.setEditable(false);
                    rectable.setEnabled(true);
                    srid.setEditable(true);
                    srfn.setEditable(true);
                    srln.setEditable(true);
                    jButton4.setEnabled(true);

                    newemp1.setEnabled(true);
                    editemp1.setEnabled(true);
                    
                    rectable.setEnabled(false);
                    
                    save1.setEnabled(false);
                    cancel1.setEnabled(false);
            }
        }else if(state == 2){
            int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to update the status of this employee?","Update Record",JOptionPane.YES_NO_OPTION);
            if(p == 0){
                if(li.isSelected()){
                    try{
                        conn = db.db();
                        pst = conn.prepareStatement("UPDATE payroll_schema.timemonitor_tbl SET date_in = ?, time_in = ?, status = ?, twh = ? WHERE id = ? and date_out = ? and time_out = ?;");
                        pst.setString(1, dtin.getText());
                        pst.setString(2, ti.getText());
                        pst.setString(3, li.getText());
                        pst.setString(4, twh.getText());
                        pst.setString(5, id.getText());
                        pst.setString(6, dtout.getText());
                        pst.setString(7, to.getText());
                        pst.execute();
                        JOptionPane.showMessageDialog(null, "Update Success");
                    }
                    catch(Exception e){
                        JOptionPane.showMessageDialog(null, e);
                    }
                    id.setEditable(false);
                    fn.setEditable(false);
                    ln.setEditable(false);
                    to.setEditable(false);
                    ti.setEditable(false);
                    dtin.setEditable(false);
                    dtout.setEditable(false);
                    twh.setEditable(false);
                    rectable.setEnabled(true);
                    srid.setEditable(true);
                    srfn.setEditable(true);
                    srln.setEditable(true);
                    jButton4.setEnabled(true);


                    newemp1.setEnabled(true);
            editemp1.setEnabled(true);

                    save1.setEnabled(false);
                    cancel1.setEnabled(false);
                }else if(lo.isSelected()){
                    try{
                        conn = db.db();
                        pst = conn.prepareStatement("UPDATE payroll_schema.timemonitor_tbl SET date_out = ?, time_out = ?, status = ?, twh = ? WHERE id = ? and date_in = ? and time_in = ?;");
                        pst.setString(1, dtout.getText());
                        pst.setString(2, to.getText());
                        pst.setString(3, lo.getText());
                        pst.setString(4, twh.getText());
                        pst.setString(5, id.getText());
                        pst.setString(6, dtin.getText());
                        pst.setString(7, ti.getText());
                        pst.execute();
                        JOptionPane.showMessageDialog(null, "Update Success");
                    }
                    catch(Exception e){
                        JOptionPane.showMessageDialog(null, e);
                    }
                    String hour = ti.getText().substring(0, 2);//first
                    String min = ti.getText().substring(3, 5);//first

                    String hour1 = to.getText().substring(0, 2);//second
                    String min1 = to.getText().substring(3, 5);//second

                    Integer hours = Integer.parseInt(hour);//first
                    Integer mins = Integer.parseInt(min);//first

                    Integer hours1 = Integer.parseInt(hour1);//second
                    Integer mins1 = Integer.parseInt(min1);//second
                    
                    if(hours == hours1){
                        int timemin = mins1 -mins ;
                        if(timemin < 60){
                           timeHour = 1;
                        }
                     }else if(hours < hours1 && mins1 <= 30){
                         timeHour = hours1 - hours;
                     }else if(hours < hours1 && mins1 > 30){
                         timeHour = hours1 - hours + 1;
                     }else if(hours1 > 0 && hours1 < hours && mins1 > 30){
                         timeHour =  ((24 - hours) + hours1)+1;
                     }else if(hours1 > 0 && hours1 < hours && mins1 < 30){
                         timeHour =  (24 - hours) + hours1;
                     }
                    
                    try{
                        conn = db.db();
                        pst = conn.prepareStatement("UPDATE payroll_schema.overtime_tbl SET ot_date = ?, ot_login = ?, ot_logout = ?, twh = ? where id = ? and lastname = ? and  firstname = ? and ot_date = ? and ot_login = ? and ot_logout = ?;");
                        pst.setString(5, id.getText());
                        pst.setString(6, ln.getText());
                        pst.setString(7, fn.getText());
                        pst.setString(4, String.valueOf(timeHour));
                        pst.setString(2, ti.getText());
                        pst.setString(3, to.getText());
                        pst.setString(1, dtin.getText());
                        pst.setString(9, ti.getText());
                        pst.setString(10, to.getText());
                        pst.setString(8, dtin.getText());
                        pst.execute();
                        }
                      catch(Exception e){
                          JOptionPane.showMessageDialog(null, "3");
                      }
                    id.setEditable(false);
                    fn.setEditable(false);
                    ln.setEditable(false);
                    to.setEditable(false);
                    ti.setEditable(false);
                    dtin.setEditable(false);
                    dtout.setEditable(false);
                    twh.setEditable(false);
                    rectable.setEnabled(true);
                    srid.setEditable(true);
                    srfn.setEditable(true);
                    srln.setEditable(true);
                    jButton4.setEnabled(true);

                    newemp1.setEnabled(true);
            editemp1.setEnabled(true);


                    save1.setEnabled(false);
                    cancel1.setEnabled(false);
                }
            }
        }
    }//GEN-LAST:event_save1ActionPerformed

    private void cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel1ActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Do you want to cancel?","Caution",JOptionPane.YES_NO_OPTION);
        if(p == 0){
            id.setEditable(false);
            fn.setEditable(false);
            ln.setEditable(false);
            to.setEditable(false);
            ti.setEditable(false);
            dtin.setEditable(false);
            dtout.setEditable(false);
            twh.setEditable(false);
            rectable.setEnabled(true);
            srid.setEditable(true);
            srfn.setEditable(true);
            srln.setEditable(true);
            jButton4.setEnabled(true);
            lo.setSelected(false);
            li.setSelected(false);
            save1.setEnabled(false);
            cancel1.setEnabled(false);
            newemp1.setEnabled(true);
            editemp1.setEnabled(true);
            id.setText("");
            fn.setText("");
            ln.setText("");
            to.setText("");
            ti.setText("");
            dtin.setText("");
            dtout.setText("");
            twh.setText("");
            
            srid.setText("");
            srfn.setText("");
            srln.setText("");
            ph = new PlaceHolder(srid, "ID");
            ph = new PlaceHolder(srln, "Last Name");
            ph = new PlaceHolder(srfn, "First Name");
        }
    }//GEN-LAST:event_cancel1ActionPerformed

    private void idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_idKeyPressed

    private void idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyReleased
        // TODO add your handling code here:
        if(id.getText().equals("")){
            ln.setText("");
            fn.setText("");
        }else{
        try{
            conn = db.db();
            pst = conn.prepareStatement("SELECT * FROM payroll_schema.emp_tbl where emp_id = ?");
            pst.setString(1, id.getText());
            rs = pst.executeQuery();
            while(rs.next()){
                ln.setText(rs.getString("lastname"));
                fn.setText(rs.getString("firstname"));
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_idKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(timemonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(timemonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(timemonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(timemonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                timemonitor dialog = new timemonitor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel1;
    private javax.swing.JTextField dtin;
    private javax.swing.JTextField dtout;
    private javax.swing.JButton editemp1;
    private javax.swing.JTextField fn;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox li;
    private javax.swing.JTextField ln;
    private javax.swing.JCheckBox lo;
    private javax.swing.JButton newemp1;
    private javax.swing.JTable rectable;
    private javax.swing.JButton save1;
    private javax.swing.JTextField srfn;
    private javax.swing.JTextField srid;
    private javax.swing.JTextField srln;
    private javax.swing.JTextField ti;
    private javax.swing.JTextField to;
    private javax.swing.JTextField twh;
    // End of variables declaration//GEN-END:variables
}
